system:
    default:
        fieldtypes:
            ezrichtext:
                custom_tags:
                    ezyoutube:
                        attributes:
                            title:
                                type: 'string'
                                required: true
                                default_value: ''
                            inline:
                                type: 'boolean'
                                required: false
                                default_value: true
                            limit:
                                type: 'number'
                                required: false
                                default_value: 5
                            cssClass:
                                type: 'choice'
                                required: true
                                default_value: ''
                                choices:
                                    - 'super-class'
                                    - 'extra-class'
                                    - 'super-extra-class'

                    eztwitter:
                        attributes:
                            title:
                                type: 'string'
                                required: true
                                default_value: ''
                            inline:
                                type: 'boolean'
                                required: false
                                default_value: true
                            limit:
                                type: 'number'
                                required: false
                                default_value: 5
                            cssClass:
                                type: 'choice'
                                required: true
                                default_value: ''
                                choices:
                                    - 'super-class'
                                    - 'extra-class'
                                    - 'super-extra-class'
