services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformAdminUi\Strategy\NotificationTwigStrategy: ~

    EzSystems\EzPlatformAdminUi\Strategy\ContentTypeThumbnailStrategy:
        tags:
            - { name: kernel.thumbnail_strategy, priority: -100 }
